"""
International Morse Code Standards:
    1 dash = 3 dots
    The space between parts of the same letter = 1 dot
    The space between letters = 3 dots (1 dash)
    The space between words = 7 dots
    Frequency Standard: 700 Hz
    Speed Standard: 20 wpm
"""

import I2C_LCD_driver
import RPi.GPIO as GPIO
import time
import sys

lcd1 = I2C_LCD_driver.lcd()
GPIO.setmode(GPIO.BOARD)

ledPin = 11
buzzerPin = 12

GPIO.setup(ledPin,GPIO.OUT)
GPIO.setup(buzzerPin,GPIO.OUT)

def dot():
    GPIO.output(buzzerPin,1)
    GPIO.output(ledPin,1)
    time.sleep(0.0625)
    GPIO.output(buzzerPin,0)
    GPIO.output(ledPin,0)
    time.sleep(0.0625)

def dash():
    GPIO.output(buzzerPin,1)
    GPIO.output(ledPin,1)
    time.sleep(0.1875)
    GPIO.output(buzzerPin,0)
    GPIO.output(ledPin,0)
    time.sleep(0.0625)

def morse(i):
    if i in ['a', 'A']:
        lcd1.lcd_display_string("%c  ->  .-    " %i,2,2)
        print('\t\t '+i+' \t - \t .-   ')
        dot()
        dash()
    elif i in ['b', 'B']:
        lcd1.lcd_display_string("%c  ->  -...  " %i,2,2)
        print('\t\t '+i+' \t - \t -...')
        dash()
        dot()
        dot()
        dot()
    elif i in ['c', 'C']:
        lcd1.lcd_display_string("%c  ->  -.-.  " %i,2,2)
        print('\t\t '+i+' \t - \t -.-.')
        dash()
        dot()
        dash()
        dot()
    elif i in ['d', 'D']:
        lcd1.lcd_display_string("%c  ->  -..   " %i,2,2)
        print('\t\t '+i+' \t - \t -..')
        dash()
        dot()
        dot()
    elif i in ['e', 'E']:
        lcd1.lcd_display_string("%c  ->  .     " %i,2,2)
        print('\t\t '+i+' \t - \t .')
        dot()
    elif i in ['f', 'F']:
        lcd1.lcd_display_string("%c  ->  ..-.  " %i,2,2)
        print('\t\t '+i+' \t - \t ..-.')
        dot()
        dot()
        dash()
        dot()
    elif i in ['g', 'G']:
        lcd1.lcd_display_string("%c  ->  --.   " %i,2,2)
        print('\t\t '+i+' \t - \t --.')
        dash()
        dash()
        dot()
    elif i in ['h', 'H']:
        lcd1.lcd_display_string("%c  ->  ....  " %i,2,2)
        print('\t\t '+i+' \t - \t ....')
        dot()
        dot()
        dot()
        dot()
    elif i in ['i', 'I']:
        lcd1.lcd_display_string("%c  ->  ..    " %i,2,2)
        print('\t\t '+i+' \t - \t ..')
        dot()
        dot()
    elif i in ['j', 'J']:
        lcd1.lcd_display_string("%c  ->  .---  " %i,2,2)
        print('\t\t '+i+' \t - \t .---')
        dot()
        dash()
        dash()
        dash()
    elif i in ['k', 'K']:
        lcd1.lcd_display_string("%c  ->  -.-   " %i,2,2)
        print('\t\t '+i+' \t - \t -.-')
        dash()
        dot()
        dash()
    elif i in ['l', 'L']:
        lcd1.lcd_display_string("%c  ->  .-..  " %i,2,2)
        print('\t\t '+i+' \t - \t .-..')
        dot()
        dash()
        dot()
        dot()
    elif i in ['m', 'M']:
        lcd1.lcd_display_string("%c  ->  --    " %i,2,2)
        print('\t\t '+i+' \t - \t --')
        dash()
        dash()
    elif i in ['n', 'N']:
        lcd1.lcd_display_string("%c  ->  -.    " %i,2,2)
        print('\t\t '+i+' \t - \t -.')
        dash()
        dot()
    elif i in ['o', 'O']:
        lcd1.lcd_display_string("%c  ->  ---   " %i,2,2)
        print('\t\t '+i+' \t - \t ---')
        dash()
        dash()
        dash()
    elif i in ['p', 'P']:
        lcd1.lcd_display_string("%c  ->  .--.  " %i,2,2)
        print('\t\t '+i+' \t - \t .--.')
        dot()
        dash()
        dash()
        dot()
    elif i in ['q', 'Q']:
        lcd1.lcd_display_string("%c  ->  --.-  " %i,2,2)
        print('\t\t '+i+' \t - \t --.-')
        dash()
        dash()
        dot()
        dash()
    elif i in ['r', 'R']:
        lcd1.lcd_display_string("%c  ->  .-.   " %i,2,2)
        print('\t\t '+i+' \t - \t .-.')
        dot()
        dash()
        dot()
    elif i in ['s', 'S']:
        lcd1.lcd_display_string("%c  ->  ...   " %i,2,2)
        print('\t\t '+i+' \t - \t ...')
        dot()
        dot()
        dot()
    elif i in ['t', 'T']:
        lcd1.lcd_display_string("%c  ->  -     " %i,2,2)
        print('\t\t '+i+' \t - \t -')
        dash()
    elif i in ['u', 'U']:
        lcd1.lcd_display_string("%c  ->  ..-   " %i,2,2)
        print('\t\t '+i+' \t - \t ..-')
        dot()
        dot()
        dash()
    elif i in ['v', 'V']:
        lcd1.lcd_display_string("%c  ->  ...-  " %i,2,2)
        print('\t\t '+i+' \t - \t ...-')
        dot()
        dot()
        dot()
        dash()
    elif i in ['w', 'W']:
        lcd1.lcd_display_string("%c  ->  .--   " %i,2,2)
        print('\t\t '+i+' \t - \t .--')
        dot()
        dash()
        dash()
    elif i in ['x', 'X']:
        lcd1.lcd_display_string("%c  ->  -..-  " %i,2,2)
        print('\t\t '+i+' \t - \t -..-')
        dash()
        dot()
        dot()
        dash()
    elif i in ['y', 'Y']:
        lcd1.lcd_display_string("%c  ->  -.--  " %i,2,2)
        print('\t\t '+i+' \t - \t -.--')
        dash()
        dot()
        dash()
        dash()
    elif i in ['z', 'Z']:
        lcd1.lcd_display_string("%c  ->  --..  " %i,2,2)
        print('\t\t '+i+' \t - \t --..')
        dash()
        dash()
        dot()
        dot()
    elif i in ['0']:
        lcd1.lcd_display_string("%c  ->  ----- " %i,2,2)
        print('\t\t '+i+' \t - \t -----')
        dash()
        dash()
        dash()
        dash()
        dash()
    elif i in ['1']:
        lcd1.lcd_display_string("%c  ->  .---- " %i,2,2)
        print('\t\t '+i+' \t - \t .----')
        dot()
        dash()
        dash()
        dash()
        dash()
    elif i in ['2']:
        lcd1.lcd_display_string("%c  ->  ..--- " %i,2,2)
        print('\t\t '+i+' \t - \t ..---')
        dot()
        dot()
        dash()
        dash()
        dash()
    elif i in ['3']:
        lcd1.lcd_display_string("%c  ->  ...-- " %i,2,2)
        print('\t\t '+i+' \t - \t ...--')
        dot()
        dot()
        dot()
        dash()
        dash()
    elif i in ['4']:
        lcd1.lcd_display_string("%c  ->  ....- " %i,2,2)
        print('\t\t '+i+' \t - \t ....-')
        dot()
        dot()
        dot()
        dot()
        dash()
    elif i in ['5']:
        lcd1.lcd_display_string("%c  ->  ..... " %i,2,2)
        print('\t\t '+i+' \t - \t .....')
        dot()
        dot()
        dot()
        dot()
        dot()
    elif i in ['6']:
        lcd1.lcd_display_string("%c  ->  -.... " %i,2,2)
        print('\t\t '+i+' \t - \t -....')
        dash()
        dot()
        dot()
        dot()
        dot()
    elif i in ['7']:
        lcd1.lcd_display_string("%c  ->  --... " %i,2,2)
        print('\t\t '+i+' \t - \t --...')
        dash()
        dash()
        dot()
        dot()
        dot()
    elif i in ['8']:
        lcd1.lcd_display_string("%c  ->  ---.. " %i,2,2)
        print('\t\t '+i+' \t - \t ---..')
        dash()
        dash()
        dash()
        dot()
        dot()
    elif i in ['9']:
        lcd1.lcd_display_string("%c  ->  ----. " %i,2,2)
        print('\t\t '+i+' \t - \t ----.')
        dash()
        dash()
        dash()
        dash()
        dot()
    elif i in ['.']:
        lcd1.lcd_display_string("%c  ->  .-.-.-" %i,2,2)
        print('\t\t '+i+' \t - \t .-.-.-')
        dot()
        dash()
        dot()
        dash()
        dot()
        dash()
    elif i in [',']:
        lcd1.lcd_display_string("%c  ->  --..--" %i,2,2)
        print('\t\t '+i+' \t - \t --..--')
        dash()
        dash()
        dot()
        dot()
        dash()
        dash()
    elif i in ['?']:
        lcd1.lcd_display_string("%c  ->  ..--.." %i,2,2)
        print('\t\t '+i+' \t - \t ..--..')
        dot()
        dot()
        dash()
        dash()
        dot()
        dot()
    elif i in ['@']:
        lcd1.lcd_display_string("%c  ->  -..-.-" %i,2,2)
        print('\t\t '+i+' \t - \t -..-.-')
        dash()
        dot()
        dot()
        dash()
        dot()
        dash()
    elif i in ['!']:
        lcd1.lcd_display_string("%c  ->  -.-.--" %i,2,2)
        print('\t\t '+i+' \t - \t -.-.--')
        dash()
        dot()
        dash()
        dot()
        dash()
        dash()
    elif i in ['/']:
        lcd1.lcd_display_string("%c  ->  -..-. " %i,2,2)
        print('\t\t '+i+' \t - \t -..-.')
        dash()
        dot()
        dot()
        dash()
        dot()
    elif i in [':']:
        lcd1.lcd_display_string("%c  ->  ---..." %i,2,2)
        print('\t\t '+i+' \t - \t ---...')
        dash()
        dash()
        dash()
        dot()
        dot()
        dot()
    elif i in [';']:
        lcd1.lcd_display_string("%c  ->  -.-.-." %i,2,2)
        print('\t\t '+i+' \t - \t -.-.-.')
        dash()
        dot()
        dash()
        dot()
        dash()
        dot()
    elif i in ['=']:
        lcd1.lcd_display_string("%c  ->  -...- " %i,2,2)
        print('\t\t '+i+' \t - \t -...-')
        dash()
        dot()
        dot()
        dot()
        dash()
    elif i in ['+']:
        lcd1.lcd_display_string("%c  ->  .-.-. " %i,2,2)
        print('\t\t '+i+' \t - \t .-.-.')
        dot()
        dash()
        dot()
        dash()
        dot()
    elif i in ['-']:
        lcd1.lcd_display_string("%c  ->  -....-" %i,2,2)
        print('\t\t '+i+' \t - \t -....-')
        dash()
        dot()
        dot()
        dot()
        dot()
        dash()
    elif i in ['_']:
        lcd1.lcd_display_string("%c  ->  ..--.-" %i,2,2)
        print('\t\t '+i+' \t - \t ..--.-')
        dot()
        dot()
        dash()
        dash()
        dot()
        dash()
    elif i in ['\"']:
        lcd1.lcd_display_string("%c  ->  .-..-." %i,2,2)
        print('\t\t '+i+' \t - \t .-..-.')
        dot()
        dash()
        dot()
        dot()
        dash()
        dot()
    elif i in ['\'']:
        lcd1.lcd_display_string("%c  ->  .----." %i,2,2)
        print('\t\t '+i+' \t - \t .----.')
        dot()
        dash()
        dash()
        dash()
        dash()
        dot()
    else:
        lcd1.lcd_display_string("%c  ->  N/A   " %i,2,2)
        print('\n\t\t '+i+' \t - \t N/A\n')

try:
    while True:
        lcd1.lcd_display_string("Enter any string",1,0)
        lcd1.lcd_display_string("to generate code",2,0)
        string = input('\n\t [*] Enter any string to generate Morse Code: ')
        print()
        lcd1.lcd_clear()
        for i in string:
            lcd1.lcd_display_string("Morse Code:",1,2)
            if(i==' '):
                lcd1.lcd_display_string("->",2,5)
                print('\t\t '+i+' \t -')
                time.sleep(0.4375)
            else:
                morse(i)
                time.sleep(0.1875)
except KeyboardInterrupt:
    print('\n\n\t [*] Keyboard Interrupt. Aborting !!!\n')
    lcd1.lcd_clear()
    GPIO.cleanup()